In [77]:
import numpy as np

In [78]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

In [79]:
def cross_entropy_error(y, t):
    delta = 1e-7
    return -np.sum(t * np.log(y + delta))

In [80]:
def numerical_gradient(f, x):
    h = 1e-4
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + h
        fxh1 = f(x)
        
        x[idx] = float(tmp_val) - h
        fxh2 = f(x)
        grad[idx] = (fxh1 - fxh2) / (2 * h)
        
        x[idx] = tmp_val
        it.iternext()
    return grad

In [81]:
class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2, 3)
    
    def predict(self, x):
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)
        return loss

In [82]:
net = simpleNet()
print(net.W)

[[ 0.42178952 -1.39108764 -0.51358144]
 [-2.16171743 -0.52489672 -1.09873878]]


In [83]:
x = np.array([0.6, 0.9])

In [84]:
p = net.predict(x)
np.argmax(p)

np.int64(2)

In [85]:
t = np.array([0, 0, 1])
net.loss(x, t)

np.float64(0.9795941679139389)

In [88]:
def f(W):
    return net.loss(x, t)

dW = numerical_gradient(lambda w: net.loss(x, t), net.W)
print(dW)

[[ 0.15169573  0.22302616 -0.37472189]
 [ 0.2275436   0.33453925 -0.56208284]]
