In [1]:
import numpy as np

In [2]:
def numerical_gradient(f, x):
    h = 1e-4
    grad = np.zeros_like(x)

    for idx in range(x.size):
        tmp_val = x[idx]
        x[idx] = tmp_val + h
        fxh1 = f(x)

        x[idx] = tmp_val -h
        fxh2 = f(x)

        grad[idx] = (fxh1 - fxh2) / (2*h)
        x[idx] = tmp_val
    return grad

In [3]:
def gradient_descent(f, init_x, lr=0.01, step_num=100):
    x = init_x

    for i in range(step_num):
        grad = numerical_gradient(f, x)
        x -= lr * grad
    return x

In [4]:
def func(x):
    return x[0]**2 + x[1]**2

init_x = np.array([-3.0, -4.0])
gradient_descent(func, init_x, lr=0.1)

array([-6.11110793e-10, -8.14814391e-10])

In [5]:
init_x = np.array([-3.0, -4.0])
gradient_descent(func, init_x, lr=10)

array([-2.58983747e+13,  1.29524862e+12])

In [6]:
init_x = np.array([-3.0, -4.0])
gradient_descent(func, init_x, lr=1e-10)

array([-2.99999994, -3.99999992])