In [1]:
import sys
sys.path.append("../..")

In [2]:
import numpy as np
from common.layers import MatMul

In [3]:
c = np.array([[1, 0, 0, 0, 0, 0, 0]])
W = np.random.randn(7, 3)
layer = MatMul(W)
out = layer.forward(c)

In [4]:
print(out)

[[-1.28467208 -0.31236871  0.00881346]]


In [5]:
print(W)

[[-1.28467208 -0.31236871  0.00881346]
 [ 0.8517237   0.80260893  0.35117362]
 [-1.77088339  0.73824633 -2.64538116]
 [ 1.1128839   0.58763038  0.79380275]
 [ 0.01287326 -0.14879395  0.33680531]
 [-0.48498518 -0.4472975  -0.14260649]
 [ 0.54463527  0.59979248 -0.32314239]]
